ansible_ssh_user: admin
ansible_ssh_pass: YourPaSsWoRd
ansible_ssh_extra_args: "-o StrictHostKeyChecking=no -o ConnectTimeout=30"
ansible_network_os: dellemc.enterprise_sonic.sonic

# Additional parameters for connection type httpapi
ansible_httpapi_use_ssl: true
ansible_httpapi_validate_certs: false
